### ISSUE TITLE
Package summary needs improvement

### ISSUE THREAD

**Issue by mtelka** [jaraco/pytest-perf#8]
The `pytest-perf` package summary both at pypi.org and in the `PKG-INFO` is not very descriptive:
```
$ curl -s https://pypi.org/pypi/pytest-perf/json | jq '.info.summary'
"pytest-perf"
$ grep Summary pytest-perf-0.12.1/PKG-INFO 
Summary: pytest-perf
$
```
Please change it to something more descriptive.  For example `Run performance tests against the mainline code.` (first line from `README.rst`).

Thanks.

**Comment by jaraco** [comment]
What I'd really like is for the README and summary and Github description all to share the same description.
